import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Products from "./products/Products";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Products></Products> */}
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
